### PR TITLE
Always add domain delimiter if "Domain" checkbox is selected

### PR DESCRIPTION
**Pull request by StefanBruens**
ConfigDialog::fullUsername() always adds the domain delimiter, even if
the actual domain name is empty. Not doing so results in failing
authentication for some(?) servers.

Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>

### CODE REVIEW

**Comment by gladhorn** [comment]
Maybe it could be an option to simply remove the check-box and only set it when it's filled out (so that if there's a domain set, the \\ is added, otherwise user/pw without domain is assumed).

**Comment by StefanBruens** [comment]
@gladhorn No, thats the exact opposite to whats required - the exchange server at my former university *requires* the domain delimer, even though the domain is empty.

**Comment by gladhorn** [comment]
Oh, wow, that's weird. I just used my email address and that worked nicely without specifying a domain, even though we have one set up internally.

**Comment by StefanBruens** [comment]
You can see the actual authentication steps if you add the following to ~/.config/QtProject/qtlogging.ini : 
kf5.kio.kio_http.auth=true

**Pull request merged**
